config/routes.rb
Rails.application.routes.draw do
  resources :worklogs
  resources :users
  root 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/worklog.rb
class Worklog < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @logs = Worklog.where(user_id: params[:id])
    @log_by_calendar_weeks = @logs.all.map { |log| [log.date,log.hours]}.group_by { |h,v| h.cweek}
    @per_week_total_hours = {}
    @log_by_calendar_weeks.each do |week, log|
      sum = 0
      log.each {|l| sum += l[1]}
      @per_week_total_hours[week] = sum
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :work_hours_per_day)
    end
end

app/controllers/worklogs_controller.rb
class WorklogsController < ApplicationController
  before_action :set_worklog, only: %i[ show edit update destroy ]

  # GET /worklogs or /worklogs.json
  def index
    @worklogs = Worklog.all
  end

  # GET /worklogs/1 or /worklogs/1.json
  def show
  end

  # GET /worklogs/new
  def new
    @worklog = Worklog.new
    @worklog.user_id = params[:user_id]
  end

  # GET /worklogs/1/edit
  def edit
  end

  # POST /worklogs or /worklogs.json
  def create
    @worklog = Worklog.new(worklog_params)
    @user = @worklog.user
    respond_to do |format|
      if @worklog.save
        format.html { redirect_to users_url(@user), notice: "Worklog was successfully created." }
        format.json { render :show, status: :created, location: @worklog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @worklog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /worklogs/1 or /worklogs/1.json
  def update
    respond_to do |format|
      if @worklog.update(worklog_params)
        format.html { redirect_to worklog_url(@worklog), notice: "Worklog was successfully updated." }
        format.json { render :show, status: :ok, location: @worklog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @worklog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /worklogs/1 or /worklogs/1.json
  def destroy
    @worklog.destroy

    respond_to do |format|
      format.html { redirect_to worklogs_url, notice: "Worklog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worklog
      @worklog = Worklog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def worklog_params
      params.require(:worklog).permit(:user_id, :date, :hours, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/worklogs_helper.rb
module WorklogsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorklogTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="container w-50">

  <div class="field d-flex">
    <%= form.label :name, class: "form-label p-1 m-1" %>
    <%= form.text_field :name, class: "form-control p-1 m-1" %>
  </div>

  <div class="field d-flex">
    <%= form.label :work_hours_per_day, class: "form-label p-1 m-1" %>
    <%= form.number_field :work_hours_per_day, step: 0.5, class: "form-control p-1 m-1" %>
  </div>

  <div class="actions text-end">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
</div>
<% end %>

app/views/users/edit.html.erb
<div class="container w-50">
    <h1>Editing User</h1>

    <%= render 'form', user: @user %>

    <%= link_to 'Show', @user %> |
    <%= link_to 'Back', users_path %>
</div>

app/views/users/index.html.erb
<div class="container w-50">
  <p id="notice"><%= notice %></p>

  <h1>Users</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Work hours per day</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.work_hours_per_day %></td>
          <td><%= link_to 'Add Worklog', new_worklog_path({user_id: user.id}) %></td>
          <td><%= link_to 'Show', user %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New User', new_user_path %>
</div>

app/views/users/new.html.erb
<div class="container w-50">
    <h1>New User</h1>

    <%= render 'form', user: @user %>

    <%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<div class="container w-50">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @user.name %>
  </p>

  <p>
    <strong>Work hours per day:</strong>
    <%= @user.work_hours_per_day %>
  </p>

  <h1>Logs</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Date</th>
        <th>Hours</th>
        <th>Notes</th>
      </tr>
    </thead>

    <tbody>
      <% @logs.each do |log| %>
        <tr>
          <td><%= log.date %></td>
          <td><%= log.hours %></td>
          <td><%= log.notes %></td>
        </tr>
      <% end %>
      <tr>
        <td>Total hours work</td>
        <td colspan="2" class="<%= (@user.work_hours_per_day > @logs.sum(:hours)) ? 'table-danger': 'table-success'%>"><%= @logs.sum(:hours) %></td>
      </tr>
      <% @per_week_total_hours.each do |week, hours|%>
        <tr>
          <td>Calender week <%= week %></td>
          <td colspan="2" class="<%= (@user.work_hours_per_day > hours) ? 'table-danger': 'table-success'%>"><%= hours %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%#= link_to 'Edit', edit_user_path(@user) %>
  <%= link_to 'Back', users_path %>
</div>

app/views/worklogs/_form.html.erb
<%= form_with(model: worklog, local: true) do |form| %>
  <% if worklog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(worklog.errors.count, "error") %> prohibited this worklog from being saved:</h2>

      <ul>
        <% worklog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="container w-50">
  <%= form.hidden_field :user_id, value: @worklog.user_id %>

  <div class="field">
    <%= form.label :date, class: "form-label p-1 m-1" %>
    <%= form.date_select :date, class: "form-control p-1 m-1" %>
  </div>

  <div class="field d-flex">
    <%= form.label :hours, class: "form-label p-1 m-1" %>
    <%= form.number_field :hours, step: 0.5, class: 'form-control p-1 m-1' %>
  </div>

  <div class="field d-flex">
    <%= form.label :notes,class: "form-label p-1 m-1" %>
    <%= form.text_field :notes, class: 'form-control p-1 m-1'  %>
  </div>

  <div class="actions text-end">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
</div>

<% end %>

app/views/worklogs/edit.html.erb
<h1>Editing Worklog</h1>

<%= render 'form', worklog: @worklog %>

<%= link_to 'Show', @worklog %> |
<%= link_to 'Back', users_path %>

app/views/worklogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Worklogs</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Date</th>
      <th>Hours</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @worklogs.each do |worklog| %>
      <tr>
        <td><%= worklog.user_id %></td>
        <td><%= worklog.date %></td>
        <td><%= worklog.hours %></td>
        <td><%= worklog.notes %></td>
        <td><%= link_to 'Show', worklog %></td>
        <td><%= link_to 'Edit', edit_worklog_path(worklog) %></td>
        <td><%= link_to 'Destroy', worklog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Worklog', new_worklog_path %>

app/views/worklogs/new.html.erb
<div class="container w-50">
    <h1>New Worklog</h1>

    <%= render 'form', worklog: @worklog %>

    <%= link_to 'Back', users_path %>
</div>

app/views/worklogs/show.html.erb
<div class="container w-50">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>User:</strong>
    <%= @worklog.user_id %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= @worklog.date %>
  </p>

  <p>
    <strong>Hours:</strong>
    <%= @worklog.hours %>
  </p>

  <p>
    <strong>Notes:</strong>
    <%= @worklog.notes %>
  </p>

  <%= link_to 'Edit', edit_worklog_path(@worklog) %> |
  <%= link_to 'Back', worklogs_path %>
</div>